# Generated by Django 3.1.2 on 2020-11-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictTablesIndex',
            fields=[
                ('district_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=40)),
                ('load', models.CharField(max_length=40)),
                ('integrate', models.CharField(max_length=40)),
                ('update_time', models.DateField()),
            ],
            options={
                'db_table': 'district_tables_index',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
                'ordering': ['-c_time'],
            },
        ),
    ]
